Contact-Module DEFINITIONS ::= BEGIN
    IMPORTS Recipient-Prekey-Bundle FROM Recipient-Prekey-Bundle-Module;

    Contact ::= SEQUENCE {
        label UTF8String,
        memo UTF8String,
        prekey-bundle Recipient-Prekey-Bundle
    }
END
