#ifndef constants_h
#define constants_h

#include <sodium.h>

//String Literals
#define MIST_BECH32M_HRP "mist"
#define MIST_BECH32M_HRP_CONTACT "mistcontact"
#define MIST_BECH32M_HRP_SECRET "mistsecret"
#define MIST_BECH32M_HRP_SIGNATURE "mistsign"

#define MIST_CONTACT_FIELD_SEPERATOR "\n" //Should be gotten rid of

#define MIST_SPK_IDENTIFIER_PREFIX "spk_" //Should be gotten rid of
#define MIST_PQSPK_IDENTIFIER_PREFIX "pqspk_" //Should be gotten rid of
#define MIST_SK_IDENTIFIER_PREFIX "sk_" //Should be gotten rid of

//Sizes
#define MIST_ED25519_PK_SIZE crypto_sign_ed25519_PUBLICKEYBYTES
#define MIST_ED25519_SK_SIZE crypto_sign_ed25519_SECRETKEYBYTES

#define MIST_X25519_PK_SIZE crypto_box_PUBLICKEYBYTES
#define MIST_X25519_SK_SIZE crypto_box_SECRETKEYBYTES

#define MIST_MLKEM768_PK_SIZE crypto_kem_mlkem768_PUBLICKEYBYTES
#define MIST_MLKEM768_SK_SIZE crypto_kem_mlkem768_SECRETKEYBYTES
#define MIST_MLKEM768_CT_SIZE crypto_kem_mlkem768_CIPHERTEXTBYTES
#define MIST_MLKEM768_SS_SIZE crypto_kem_mlkem768_SHAREDSECRETBYTES

#define MIST_XEDDSA_NONCE_SIZE 8
#define MIST_XEDDSA_SIGNATURE_SIZE 64

#define MIST_SEED_SIZE 64
#define MIST_SEED_ENTROPY_SIZE 20
#define MIST_SEED_CHECKSUM_INPUT_SIZE (MIST_SEED_ENTROPY_SIZE / 4) //Entropy size divided by 32 bits
#define MIST_SEED_MNEMONIC_WORDS (MIST_SEED_ENTROPY_SIZE - MIST_SEED_CHECKSUM_INPUT_SIZE)
#define MIST_SEED_MNEMONIC_BITS_PER_WORD 11
#define MIST_SEED_ITERATIONS 2048

#define MIST_SUBKEY_SEED_SIZE 32


#define MIST_SK_F_SIZE 32

#define MIST_KM_SECTIONS 4

#define bip39_wordlist_size 2048

//Hardcoded Values
#define bech32m_encoding "bech32"

#define MIST_SEED_MNEMONIC_SPACE " "

#define MIST_SK_F_BYTE 0xFF
#define MIST_SK_F {MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE, MIST_SK_F_BYTE}

//Enums
typedef enum {
    ed25519_algorithm,
    x25519_algorithm
} subkey_algorithm;

#endif
