#ifndef constants_h
#define constants_h

#include <sodium.h>

//String Literals
#define MIST_BECH32_HRP "mist"
#define MIST_BECH32_HRP_CONTACT "mistcontact"
#define MIST_BECH32_HRP_SECRET "mistsecret"
#define MIST_BECH32_HRP_SIGNATURE "mistsign"

#define MIST_CONTACT_FIELD_SEPERATOR "\n" //Should be gotten rid of

//Sizes
#define MIST_BECH32_MIN_HRP_LENGTH 1
#define MIST_BECH32_MAX_HRP_LENGTH 83
#define MIST_BECH32_SEPERATOR_LENGTH 1
#define MIST_BECH32_MIN_DATA_LENGTH 6
#define MIST_BECH32_CS_LENGTH 6
#define MIST_BECH32_MIN_LENGTH (MIST_BECH32_MIN_HRP_LENGTH + MIST_BECH32_SEPERATOR_LENGTH + MIST_BECH32_MIN_DATA_LENGTH + MIST_BECH32_CS_LENGTH)
#define MIST_BECH32_MAX_LENGTH 90

#define MIST_CONTACT_FIELD_SIZE 1024

#define MIST_ED25519_PK_SIZE crypto_sign_ed25519_PUBLICKEYBYTES
#define MIST_ED25519_SK_SIZE crypto_sign_ed25519_SECRETKEYBYTES

#define MIST_X25519_PK_SIZE crypto_box_PUBLICKEYBYTES
#define MIST_X25519_SK_SIZE crypto_box_SECRETKEYBYTES

#define MIST_XCHACHA20_POLY1305_NONCE_SIZE crypto_aead_xchacha20poly1305_ietf_NPUBBYTES
#define MIST_XCHACHA20_POLY1305_KEY_SIZE crypto_aead_xchacha20poly1305_ietf_KEYBYTES

#define MIST_MLKEM768_PK_SIZE crypto_kem_mlkem768_PUBLICKEYBYTES
#define MIST_MLKEM768_SK_SIZE crypto_kem_mlkem768_SECRETKEYBYTES
#define MIST_MLKEM768_CT_SIZE crypto_kem_mlkem768_CIPHERTEXTBYTES
#define MIST_MLKEM768_SS_SIZE crypto_kem_mlkem768_SHAREDSECRETBYTES

#define MIST_XEDDSA_NONCE_SIZE 8
#define MIST_XEDDSA_SIGNATURE_SIZE 64

#define MIST_DH_OUTPUT_SIZE crypto_scalarmult_BYTES

#define MIST_PQXDH_F_SIZE 32
#define MIST_PQXDH_SHARED_KEY_SIZE 32

#define bip39_wordlist_size 2048

//Hardcoded Values
#define bech32m_encoding "bech32m"

#define MIST_PQXDH_SK_F {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}

#endif
